services:
  app:
    build: .
    expose:
      - 80
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=cms_seo
      - DB_USER=admin
      - DB_PASS=senha_segura
    networks:
      - cms-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cms_seo
      MYSQL_USER: admin
      MYSQL_PASSWORD: senha_segura
      MYSQL_ROOT_PASSWORD: senha_mestra_segura
    networks:
      - cms-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  cms-network:
    driver: bridge
